dt:
  config:
    multitenant:
      mongo:
        properties:
          - tenant: pl
            properties:
              uri: mongodb://localhost:27017/devicemanagerdb_pl
              database: 2
            basePackages: com.project.multitenant.repository
      tenant:
        supportedTenants:
          - pl
          - cz
        tenantHeaders:
          - X-TENANT-ID
      feign:
        properties:
          defaults:
            enabled: true
            interval: 10
            name: some-service
            qwe: asas
eureka:
  instance:
    expire-duration: 0
