spring:
  datasource:
    url: localhost:8080/capmag
    username: rajat
management:
  endpoints:
    web:
      exposure:
        include: '*'
zuul:
  ignored-services: '*'
  prefix: /config
  routes:
    dev-manager:
      path: /custom-manager/**
      configId: custom-manager
    role-manager:
      path: /role-manager/**
      configId: role-manager
zone:
  config:
    redirection:
      prod:
        job-manager:
          url: http://config-tool/preprod/role-manager.git
        config-manager:
          url: http://config-tool/preprod/role-manager.git
      dev:
        config-manager:
          url: http://config-tool/dev/role-manager.git
        job-manager:
          url: http://config-tool/dev/role-manager.git
      test:
        config-manager:
          url: http://config-tool/test/role-manager.git
        job-manager:
          url: http://config-tool/test/role-manager.git
    country:
      management:
        countries:
          - eu
          - in
    client:
      - country: in
        type: custom
        username: in-user
        password: ps-user
      - country: pk
        type: custom
        username: pk-user
        password: pk-user
      - country: au
        type: custom
        token: token-au

    callback:
      callBackUrl:
        zl: http//git.com
        au: http//git.com
